# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pycon_schedule.Schedule')),
            ],
            options={
                'ordering': ('schedule', 'start_time', 'end_time'),
            },
        ),
        migrations.CreateModel(
            name='SlotEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycon_schedule.Location')),
                ('presentation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pycon_schedule.Presentation')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pycon_schedule.ScheduleSlot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slotevent',
            unique_together=set([('slot', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleslot',
            unique_together=set([('schedule', 'start_time', 'end_time')]),
        ),
    ]
