# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_schedule', '0002_auto_20170919_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pycon_schedule.Location'),
        ),
    ]
