# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_schedule', '0003_auto_20170930_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='slotevent',
            options={'ordering': ('location__name',)},
        ),
        migrations.AddField(
            model_name='location',
            name='track',
            field=models.CharField(blank=True, choices=[('track-1', 'Track 1'), ('track-2', 'Track 2'), ('track-3', 'Track 3'), ('tutorial', 'Tutorial')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
