# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_schedule', '0004_auto_20171002_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotevent',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='Content (FR)'),
        ),
        migrations.AlterField(
            model_name='slotevent',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content (EN)'),
        ),
    ]
