# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_schedule', '0005_auto_20171005_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotevent',
            options={'ordering': ('location__order',)},
        ),
    ]
