# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkProposal',
            fields=[
                ('proposalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_proposals.ProposalBase')),
                ('audience_level', models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate'), (2, 'Experienced')])),
                ('recording_release', models.BooleanField(default=True, help_text='By submitting your proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.')),
                ('recurring', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Have you given this talk before?', verbose_name='Previously given')),
                ('tutorial', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Would you be interested in receiving mentorship / input on your talk in advance?', verbose_name='Speaker mentorship')),
                ('duration', models.CharField(choices=[('short', 'Short (~10 minutes)'), ('medium', 'Long (~30 minutes)'), ('long', 'Classroom tutorial (~45-60 minutes)')], default='medium', max_length=16, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'talk proposal',
                'permissions': (('can_review_unbiased', 'Can review with speaker details'),),
            },
            bases=('symposion_proposals.proposalbase',),
        ),
        migrations.CreateModel(
            name='TutorialProposal',
            fields=[
                ('proposalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_proposals.ProposalBase')),
                ('audience_level', models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate'), (2, 'Experienced')])),
                ('recording_release', models.BooleanField(default=True, help_text='By submitting your proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.')),
                ('recurring', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Have you given this talk before?', verbose_name='Previously given')),
                ('tutorial', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Would you be interested in receiving mentorship / input on your talk in advance?', verbose_name='Speaker mentorship')),
                ('duration', models.CharField(choices=[('short', 'Short (~10 minutes)'), ('medium', 'Long (~30 minutes)'), ('long', 'Classroom tutorial (~45-60 minutes)')], default='medium', max_length=16, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'tutorial proposal',
            },
            bases=('symposion_proposals.proposalbase',),
        ),
    ]
