# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PySponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('twitter_username_en', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_username_fr', models.CharField(blank=True, default='', max_length=255)),
                ('url_en', models.URLField(blank=True, null=True)),
                ('url_fr', models.URLField(blank=True, null=True)),
                ('logo_en', models.FileField(blank=True, upload_to='sponsor_files', verbose_name='Logo EN')),
                ('logo_fr', models.FileField(blank=True, upload_to='sponsor_files', verbose_name='Logo FR')),
                ('active', models.BooleanField(default=False)),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Internal note')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PySponsorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description_en', models.TextField(default='')),
                ('description_fr', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='pysponsor',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='py_sponsors', to='pycon_sponsors.PySponsorLevel'),
        ),
    ]
