# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon_sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pysponsorlevel',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pysponsorlevel',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
